# Generated by Django 5.2.4 on 2025-07-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressTemp',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='LettingTemp',
            new_name='Letting',
        ),
    ]
