# Generated by Django 5.2.4 on 2025-07-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
    ]
